Metropolia Ammattikorkeakoulu   
Cognitive Systems Mathematics and Methods   
Mathematics / Python Exercises 1: Exercise 6

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
A = np.array([[1, 0], [0, 2], [3, 0]])
B = np.array([[0, 4], [0, 5], [6, 0]])
B

array([[0, 4],
       [0, 5],
       [6, 0]])

In [11]:
C= np.concatenate((A, B), axis=1)
C

array([[1, 0, 0, 4],
       [0, 2, 0, 5],
       [3, 0, 6, 0]])

In [12]:
D = np.concatenate((A, B), axis=0)
D

array([[1, 0],
       [0, 2],
       [3, 0],
       [0, 4],
       [0, 5],
       [6, 0]])