Metropolia Ammattikorkeakoulu   
Cognitive Systems Mathematics and Methods   
Mathematics / Python Exercises 3: Exercise 1

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [28]:
data = np.loadtxt('fish.txt', skiprows=37)
X = data[:, 1:3]
y = data[:, 3:]
X1 = np.concatenate((np.ones((44,1)), X), axis=1)
X1

array([[   1.,   14.,   25.],
       [   1.,   28.,   25.],
       [   1.,   41.,   25.],
       [   1.,   55.,   25.],
       [   1.,   69.,   25.],
       [   1.,   83.,   25.],
       [   1.,   97.,   25.],
       [   1.,  111.,   25.],
       [   1.,  125.,   25.],
       [   1.,  139.,   25.],
       [   1.,  153.,   25.],
       [   1.,   14.,   27.],
       [   1.,   28.,   27.],
       [   1.,   41.,   27.],
       [   1.,   55.,   27.],
       [   1.,   69.,   27.],
       [   1.,   83.,   27.],
       [   1.,   97.,   27.],
       [   1.,  111.,   27.],
       [   1.,  125.,   27.],
       [   1.,  139.,   27.],
       [   1.,  153.,   27.],
       [   1.,   14.,   29.],
       [   1.,   28.,   29.],
       [   1.,   41.,   29.],
       [   1.,   55.,   29.],
       [   1.,   69.,   29.],
       [   1.,   83.,   29.],
       [   1.,   97.,   29.],
       [   1.,  111.,   29.],
       [   1.,  125.,   29.],
       [   1.,  139.,   29.],
       [   1.,  153.,   29.],
       [  

In [31]:
M = np.linalg.inv(np.dot(X.T, X)).dot(X.T).dot(y)
M

array([[ 27.27954198],
       [ 29.07413117]])

In [38]:
y_estimate = X.dot(M)
results = np.concatenate((y, y_estimate, y_estimate - y), axis=1)
results

array([[  620.        ,  1108.76686697,   488.76686697],
       [ 1315.        ,  1490.68045472,   175.68045472],
       [ 2120.        ,  1845.31450049,  -274.68549951],
       [ 2600.        ,  2227.22808825,  -372.77191175],
       [ 3110.        ,  2609.141676  ,  -500.858324  ],
       [ 3535.        ,  2991.05526375,  -543.94473625],
       [ 3935.        ,  3372.9688515 ,  -562.0311485 ],
       [ 4465.        ,  3754.88243925,  -710.11756075],
       [ 4530.        ,  4136.796027  ,  -393.203973  ],
       [ 4570.        ,  4518.70961476,   -51.29038524],
       [ 4600.        ,  4900.62320251,   300.62320251],
       [  625.        ,  1166.91512931,   541.91512931],
       [ 1215.        ,  1548.82871706,   333.82871706],
       [ 2110.        ,  1903.46276283,  -206.53723717],
       [ 2805.        ,  2285.37635058,  -519.62364942],
       [ 3255.        ,  2667.28993833,  -587.71006167],
       [ 4015.        ,  3049.20352609,  -965.79647391],
       [ 4315.        ,  3431.1

In [37]:
results.shape

(44, 3)

In [39]:
print('Linear regression mean absolute error:', np.sum(np.abs(y_estimate - y))/44)

Linear regression mean absolute error: 534.722049449
