Metropolia Ammattikorkeakoulu   
Cognitive Systems Mathematics and Methods   
Mathematics / Python Exercises 2: Exercise 1

In [93]:
import numpy as np
import matplotlib.pyplot as plt


In [124]:
A = np.ones((1,1))
A1 = np.concatenate((A, A**2, A**3, A**4, A**5))
A1

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [123]:
B1 = A
B2 = A*2
B3 = A*3
B4 = A*4
B5 = A*5
B = np.concatenate((B1, B2, B3, B4, B5))
B


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.]])

In [128]:
C = B**2
C

array([[  1.],
       [  4.],
       [  9.],
       [ 16.],
       [ 25.]])

In [129]:
D = B**3
D

array([[   1.],
       [   8.],
       [  27.],
       [  64.],
       [ 125.]])

In [131]:
E = B**4
E

array([[   1.],
       [  16.],
       [  81.],
       [ 256.],
       [ 625.]])

In [133]:
F = np.concatenate((A1, B, C, D, E), axis = 1)
F

array([[   1.,    1.,    1.,    1.,    1.],
       [   1.,    2.,    4.,    8.,   16.],
       [   1.,    3.,    9.,   27.,   81.],
       [   1.,    4.,   16.,   64.,  256.],
       [   1.,    5.,   25.,  125.,  625.]])