Metropolia Ammattikorkeakoulu   
Cognitive Systems Mathematics and Methods   
Mathematics / Python Exercises 1: Exercise 1   

In [2]:
import numpy as np
import matplotlib.pyplot as plt

Exercise 1

a)

In [35]:
A = np.array([[3, 6]])
B = np.array([[5], [2]])
np.dot(A, B)

array([[27]])

b)

In [36]:
np.dot(B,A)

array([[15, 30],
       [ 6, 12]])

c)

In [38]:
C = np.array([[3],[6]])
np.dot(B,C)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

d)

In [41]:
D=np.array([[1, 2],[3, 5]])
E = np.array([[4],[6]])
np.dot(D,E)

array([[16],
       [42]])

e)

In [46]:
F = np.array([[4, 6]])
G = np.array([[1, 2],[3,5]])
np.dot(F,G)

array([[22, 38]])

f)

In [52]:
ET = E.T
np.dot(np.dot(ET,D),E)

array([[316]])