Metropolia Ammattikorkeakoulu   
Cognitive Systems Mathematics and Methods   
Mathematics / Python Exercises 1: Exercise 2

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
A = np.array([[1, 0], [0, 2], [3, 0]])
B = np.array([[0, 4], [0, 5], [6, 0]])

a)

In [5]:
np.dot(A, B)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

b)

In [6]:
A * B

array([[ 0,  0],
       [ 0, 10],
       [18,  0]])

c)

In [11]:
AT = A.T
np.dot(AT, B)

array([[18,  4],
       [ 0, 10]])

d)

In [9]:
BT = B.T
np.dot(A, BT)

array([[ 0,  0,  6],
       [ 8, 10,  0],
       [ 0,  0, 18]])

e)

In [12]:
np.dot(10, A)

array([[10,  0],
       [ 0, 20],
       [30,  0]])

f)

In [14]:
10 + A 

array([[11, 10],
       [10, 12],
       [13, 10]])